name: MedievalKingdoms
version: 2.0.0
main: com.medieval.MedievalKingdoms
api-version: 1.21
author: YourName
description: Medieval Kingdom Management Plugin

commands:
  kingdom:
    description: Main kingdom command
    aliases: [k]
  vote:
    description: Voting commands
    aliases: [v]
  role:
    description: Role management

permissions:
  medieval.*:
    default: op
